### ISSUE TITLE
В провайдере OfdRu нужно вынести Num в переменную

### ISSUE THREAD

**Issue by crow2k** [sergelevin/pyofd#1]
без него ofd.ru не возвращает чек

**Comment by crow2k** [comment]
GET https://ofd.ru/api/rawdoc/RecipeInfo?Fn=8710000100617432&Kkt=0000489397013091&Inn=7814339162&Num=7481&Sign=2981623349
чек нашел в проекте

**Comment by sergelevin** [comment]
Так он как раз успешно возвращался с сервера ОФД, т.к. был удачно захордкожен правильный Num. Я же просил пример данных, который до моей правки db2d3ea не возвращались с сервера, а после неё стали возвращаться.

**Comment by crow2k** [comment]
Извиняюсь, сразу не понял.
Можно взять такой чек GET https://ofd.ru/api/rawdoc/RecipeInfo?Fn=8710000100767988&Kkt=0000520679026739&Inn=7825439514&Num=160669&Sign=1626880333

**Comment by sergelevin** [comment]
Спасибо. Возможно, я сам криво фразу построил какой именно чек я жду.
Чек включил в тесты.  Само исправление уже опубликовано на pypi начиная с pyofd-0.1.3 и доступно здесь в ветке master.
